### ISSUE TITLE
Include the example folder?

### ISSUE THREAD

**Issue by arnthor3** [datchley/react-scale-text#10]
Hi,
I am in the middle of fixing the dependencies but I am missing the examples folder. Could you include it? I noticed it's not excluded in the .gitignore file.

```js
start: "npm install && cd examples/simple && npm install && npm start"
```
The project looks nice btw.
-A

**Comment by datchley** [comment]
We just released 1.1.4 which should work with React 16 and latest babel.  Are you working on other dependencies?

**Comment by datchley** [comment]
And, actually, I think that `example` folder is a hold over from the earliest part of the project.  We're really just using the `docs/` folder now and don't include a running example.  I'll put in a PR to remove that this evening so it's not confusing.

**Comment by arnthor3** [comment]
I was in the middle of getting the dependencies updated, so I am really glad that you are on top of things here. I will close this as this is a non issue.
