### ISSUE TITLE
Incomplete with react 16.0

### ISSUE THREAD

**Issue by maZahaca** [datchley/react-scale-text#9]
Hi,
I've just checked on react 16.0 branch and getting many errors,
at least one about using PropTypes as from separate repo.

**Comment by datchley** [comment]
Getting ready to merge in #12 which is a dependency upgrade to support React 16, which should correct this issue.

**Comment by datchley** [comment]
We've got 1.1.4 out now which should correct these issues. I'm going to close this; but feel free to reopen if you're still seeing problems.
